alias c := clean_build
alias b := build
alias i := install
alias r := rebuild
alias g := gen_compile_commands

build *CMAKE_VARS:
    mkdir -p build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=~/root-filetree/devel/install {{CMAKE_VARS}} .. && \
    cmake --build .

install:
    cd build && make install


clean_build:
    rm -rf build/

gen_compile_commands:
    #!/usr/bin/env bash
    set -euxo pipefail
    if [ ! -f "build/compile_commands.json" ]; then
        echo "compile_commands.json not found in build/. Generating"
        mkdir -p build && cd build && \
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..
    else
        echo "compile_commands.json already existing. Run regen_compile_commands if want to clean and regenerate"
    fi
    cp -f compile_commands.json ..

rebuild: clean_build build
